CodeScout:
  clientType: sse
  headers: null
  name: Code Scout
  url: http://0.0.0.0:1338/sse
RefactoringCrewAgent:
  clientType: sse
  headers: null
  name: RefactoringCrewAgent
  url: http://0.0.0.0:1337/sse
